"use client";

import { useEffect, useMemo, useState } from "react";
import { RefreshCw, Trophy } from "lucide-react";
import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { GlassCard } from "@/components/ui/glass-card";
import { GlowButton } from "@/components/ui/glow-button";
import { calculateStandings, fetchLeagueData, type Fixture, type League, type Team } from "@/lib/league-data";

export default function StandingsPage() {
  const [data, setData] = useState<{ leagues: League[]; teams: Team[]; fixtures: Fixture[] } | null>(null);
  const [leagueId, setLeagueId] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setData(await fetchLeagueData()); } catch { setError("Standings could not be loaded. Check the Supabase connection and try again."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const table = useMemo(() => calculateStandings(data?.teams ?? [], data?.fixtures ?? [], leagueId === "all" ? undefined : leagueId), [data, leagueId]);
  return <DashboardLayout><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="mb-2 flex items-center gap-3"><Trophy className="h-8 w-8 text-accent" /><h1 className="text-4xl font-bold">League Table</h1></div><p className="text-foreground/60">Calculated from completed fixture results.</p></div><div className="flex gap-3"><select aria-label="Select league" value={leagueId} onChange={(e) => setLeagueId(e.target.value)} className="rounded-lg border border-border bg-background px-3 py-2 text-sm"><option value="all">All leagues</option>{data?.leagues.map((league) => <option key={league.id} value={league.id}>{league.name} · {league.season}</option>)}</select><GlowButton onClick={load} variant="outline"><RefreshCw className="mr-2 h-4 w-4" />Refresh</GlowButton></div></div>
    {loading ? <GlassCard className="p-10 text-center">Calculating standings…</GlassCard> : error ? <GlassCard className="p-10 text-center"><p className="text-red-300">{error}</p><GlowButton className="mt-4" onClick={load}>Try again</GlowButton></GlassCard> : <GlassCard animated={false}><div className="overflow-x-auto"><table className="w-full min-w-[680px]"><caption className="sr-only">League standings table</caption><thead><tr className="border-b border-primary/10 text-left text-sm text-foreground/60"><th className="px-5 py-4">Pos</th><th className="px-5 py-4">Team</th><th className="px-5 py-4 text-center">P</th><th className="px-5 py-4 text-center">W</th><th className="px-5 py-4 text-center">D</th><th className="px-5 py-4 text-center">L</th><th className="px-5 py-4 text-center">GD</th><th className="px-5 py-4 text-right">Pts</th></tr></thead><tbody>{table.map((row) => <tr key={row.team.id} className="border-b border-primary/10 transition-colors hover:bg-white/5"><td className="px-5 py-4"><span className={`inline-flex h-8 w-8 items-center justify-center rounded-full font-bold ${row.rank === 1 ? "bg-yellow-500/80 text-yellow-950" : row.rank === 2 ? "bg-slate-300 text-slate-900" : row.rank === 3 ? "bg-orange-500/80 text-orange-950" : "bg-primary/20 text-primary"}`}>{row.rank}</span></td><td className="px-5 py-4"><p className="font-semibold">{row.team.name}</p><p className="text-xs text-foreground/50">{row.team.short_name}</p></td><td className="px-5 py-4 text-center">{row.played}</td><td className="px-5 py-4 text-center text-green-300">{row.wins}</td><td className="px-5 py-4 text-center text-blue-300">{row.draws}</td><td className="px-5 py-4 text-center text-red-300">{row.losses}</td><td className="px-5 py-4 text-center text-primary">{row.goalDiff > 0 ? `+${row.goalDiff}` : row.goalDiff}</td><td className="px-5 py-4 text-right text-lg font-bold text-accent">{row.points}</td></tr>)}</tbody></table>{table.length === 0 && <p className="p-10 text-center text-foreground/60">No teams are available for this league.</p>}</div></GlassCard>}
  </DashboardLayout>;
}
